//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }


//login
# POST http://localhost:8000/authentication/login
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

//auth
# POST http://localhost:8000/api/dashboard/teacher
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUm9sZSI6IlRlYWNoZXIiLCJpYXQiOjE2NTY2NTYyMTF9.Iy30yXpI7VMTq3CnYDIyQrl2hVnZ7VFFr5kmJJicezA

//teacher create student
# POST http://localhost:8000/dashboard/teacher/student/create-student
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTc3NTR9.FWH2aw2CU47RDU2rKXUb672j53RjRUVfQ_Td9PdptgE

# {
#     "student_fullname": "Trats",
#     "student_age": 18,
#     "student_gender" : true,
#     "student_image": "image link",
#     "student_behavior": "Trungbinh",
#     "class_id": "62bec1eace300d797af8a13b",
#     "score_id": "62c260a9a2d8363660d1ec04",
#     "schoolyear_id":"62c2868129241dfd205bff4d"
# }
//teacher get student
GET http://localhost:8000/dashboard/teacher/student/get-all-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTgwNTh9.4i2-Q0YM5Zss8XzmbtFJJIMTg-f87GGj1UfBMfsVb4A

//teacher create class
# POST http://localhost:8000/dashboard/teacher/class/create-class
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTY1NTd9.pReRK2iynE4IGbukqPh9kFrtForaH0D2OXg7qek4W-M

# {
#     "class_name": "5"
# }

//teacher create score
# POST http://localhost:8000/dashboard/teacher/create-score
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJlNTNkZWNmNDFkNTY3MGVkYmEyYTMiLCJpYXQiOjE2NTY5MDU0NDR9.yk8IEbxGak17xxRZJKGbthe8PnFqY6nkKnjv8f850yQ

# {
#     "score_ratio1": "3",
#     "score_ratio2": "4",
#     "score_ratio3": "5"

# }

//teacher create school year
# POST http://localhost:8000/dashboard/teacher/create-schoolyear
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJlNTNkZWNmNDFkNTY3MGVkYmEyYTMiLCJpYXQiOjE2NTY5MDU0NDR9.yk8IEbxGak17xxRZJKGbthe8PnFqY6nkKnjv8f850yQ

# {
#     "schoolyear_name": "2022-2021"
# }