GET http://localhost:8000/dashboard/teacher/student/get-all-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTgwNTh9.4i2-Q0YM5Zss8XzmbtFJJIMTg-f87GGj1UfBMfsVb4A

###

//create class
POST http://localhost:8000/dashboard/teacher/class/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTgwNTh9.4i2-Q0YM5Zss8XzmbtFJJIMTg-f87GGj1UfBMfsVb4A

{
  "class_name": "1A"
}

###

//get class
GET http://localhost:8000/dashboard/teacher/class/

###
//update class

PUT http://localhost:8000/dashboard/teacher/class/62c3da6a9eb7d065928174ac
Content-Type: application/json

{
  "class_name": "1B"
}

###

###

//get Parent
GET http://localhost:8000/api/admin/parents



###

//update parent
PUT http://localhost:8000/api/admin/parents/62c2ae5239a7880ce4a38690
Content-Type: application/json

{
  "parent_password": "$argon2i$v=19$m=4096,t=3,p=1$xvJ6MwGPuABHfTL0BolSkQ$kdyIb4Mzyc5xLlmM0uC7sGbJm2BcucuFIAMx2RPyA18",
  "parent_name": "dddsad",
  "parent_dateofbirth": null,
  "parent_address": "sadasd",
  "parent_phone": "123qweasdf",
  "parent_email": "3",
  "parent_job": "IT",
  "parent_gender": false
}
