//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "keren@gmail.com",
    "password": "123456"
}
###
//logoout
GET http://localhost:8000/api/authentication/logout
Content-Type: application/json
###
//teacher create student by classID and parent id
POST http://localhost:8000/api/student/62da59e20bdba5be45e6b9f6&62c68c94bede51076338890a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTEyOTAyfQ.LEfbDfTcV-jXcCrG3cAazCbNS4fRBugQZqdhc0eR1So

{
    "student_fullname" : "Chris Evan test 3",
    "student_dateofbirth": "2020-05-11T20:14:14.796Z",
    "student_age":20,
    "student_gender":false,
    "student_image": "image link"
}
###
//get all student
GET http://localhost:8000/api/student/get-all-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

###
//teacher get student by teacher id
GET http://localhost:8000/api/student/get-student-by-teacher-id/62c68ad4bede5107633888f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTgzMDc5NzR9.7z8REzGVhH4xQLg7cy8fvqOl3PsBixm9HQDPnFnpYMc
###
//parent get student information by student id
GET http://localhost:8000/api/student/parent-get-student-information/62cbc71228ed8bda747c4445
Content-Type: application/json
###
//parent get student score information by student id
GET http://localhost:8000/api/student/parent-get-detailed-score-information/62df8906bfeef3904cc3a0c2
Content-Type: application/json
###
//teacher update student by id_student and parent id and class id
PUT http://localhost:8000/api/student/62df912835e45f351a0e93eb&62c68c94bede51076338890a&62da59e20bdba5be45e6b9f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

{
    "student_fullname": "Jane Mighty Thor",
    "student_dateofbirth": "2019-05-11T20:14:14.796Z",
    "student_age": 17,
    "student_gender" : false,
    "student_image": "image link !"
}
###
//teacher delete student
DELETE  http://localhost:8000/api/student/62df91905fb05fe06de52cda
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4
