//create teacher
POST http://localhost:8000/api/admin/teachers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3ODc0ODM3fQ.9JhTeeaGsDURamjVZrGeinDHOB4xO9YR6SYaYF6bbS8

{
    "teacher_name" : "Leo1",
    "teacher_age" : 75,
    "teacher_gender" : true, 
    "teacher_phone" : "0914056098",
    "is_main_teacher" : false,
    "is_user_teacher" : true,
    "teacher_email" : "leoteacher1@gmail.com",
    "teacher_password" : "123456",
    "teacher_img":""
}
###
//get all (Admin)
GET http://localhost:8000/api/admin/teachers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NDcyMDk4fQ.TtHdSeMCbgHql_j9cgOyZD0XBQx4BQoeRo6NypzHoOE


###
// get teacher by id
GET http://localhost:8000/api/admin/teachers/62c68ad4bede5107633888f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NzE0MzIwfQ.q04B8wBPSj4JUz-0AfTt2bGoUhEJ8VO_9RZ_s7_Nhpc

###
// Edit
PUT http://localhost:8000/api/admin/teachers/62c68ad4bede5107633888f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3ODc0ODM3fQ.9JhTeeaGsDURamjVZrGeinDHOB4xO9YR6SYaYF6bbS8

{
    "teacher_name" : "Ninh Khánh DUy",
    "teacher_age" : 45,
    "teacher_gender" : true, 
    "teacher_phone" : "0914056098",
    "is_main_teacher" : false,
    "is_user_teacher" : true,
    "teacher_email" : "nkd@gmail.com",
    "teacher_password" : "123456",
    "teacher_img":""
}

###
//get all (Admin)
GET http://localhost:8000/api/admin/teachers/get-teacher/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NDcyMDk4fQ.TtHdSeMCbgHql_j9cgOyZD0XBQx4BQoeRo6NypzHoOE
