//login

// account teacher
#Authorization: Bearer {{ teacher token }}
POST http://localhost:8000/api/authentication/login/
Content-Type: application/json

{
    "email": "keren@gmail.com",
    "password": "123456"
}
###
//add teacher to class
#GET http://localhost:8000/api/teacher/class/add-teacher-to-class/{{ classId }}&{{ teacherId }}
GET http://localhost:8000/api/teacher/class/add-teacher-to-class/62c69e80db14d59b81b46a71&62c68b2abede5107633888fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc4NTE0ODF9.WB3Vm4A-wRtTE_d-1-oAwJ0hvD8XXERAWcJ0ArXTPvw

###
//add schedule to class
#GET http://localhost:8000/api/teacher/class/add-schedule-to-class/{{ classId }}&{{ scheduleId }}
GET http://localhost:8000/api/teacher/class/add-schedule-to-class/62c69e1ddb14d59b81b46a67&62c7b0169d8181aea0858fd4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTcwODk0MTV9.JHRY3_KWwoyG8g4e0QNFiwXzGH6AUsannP8BWEc9lKs

###
//add student to class
#GET http://localhost:8000/api/teacher/class/add-student-to-class/{{ classId }}&{{ studentId }}
GET http://localhost:8000/api/teacher/class/add-student-to-class/62c6999ebe8c86c9d3579865&62cf8ed35de98295391348ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NDcyMDk4fQ.TtHdSeMCbgHql_j9cgOyZD0XBQx4BQoeRo6NypzHoOE

###
//teacher create class
#POST http://localhost:8000/api/teacher/class/{{ gradeId }}&{{ teacherId }}
POST http://localhost:8000/api/teacher/class/62c6999ebe8c86c9d3579865&62cf8ed35de98295391348ee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
    "class_name": "E"
}


###
//Get all class
GET http://localhost:8000/api/teacher/class/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

###
//Get class from teacher
#GET http://localhost:8000/api/teacher/class/teacher/{{ teacherId }}
GET http://localhost:8000/api/teacher/class/teacher/62c68ad4bede5107633888f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4MzA3OTAwfQ.ahcVi2rbv1lCEVYn8k5kEUuP2pYbH0-9zD-Vf13GXaU

###
//Update class
#PUT http://localhost:8000/api/teacher/class/{{ class_id }}
PUT http://localhost:8000/api/teacher/class/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTcwODk0MTV9.JHRY3_KWwoyG8g4e0QNFiwXzGH6AUsannP8BWEc9lKs

{
  "class_name": ""
}
###
//delete class
#DELETE http://localhost:8000/api/teacher/class/{{ class_id }}
DELETE http://localhost:8000/api/teacher/class/62c69e9cdb14d59b81b46a85
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMWViZWRlNTEwNzYzMzg4OTE0IiwiaWF0IjoxNjU4MjE3NzA1fQ.4OkN94PrFVZI7Zq_YKrfd8cilaJVIwEuC4_2v2LMAXE

###
// get class by gradeID
GET http://localhost:8000/api/teacher/class/grade/62c6999bbe8c86c9d3579862
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMWViZWRlNTEwNzYzMzg4OTE0IiwiaWF0IjoxNjU4MjE3NzA1fQ.4OkN94PrFVZI7Zq_YKrfd8cilaJVIwEuC4_2v2LMAXE
