//get all Public Notification
GET http://localhost:8000/api/notification/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


###
//get Notification by id
GET http://localhost:8000/api/notification/62ccf976f0b91fba281523e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


###
//get Private Notification of teacher
#GET http://localhost:8000/api/notification/teacher/{{ teacher_id }}
GET http://localhost:8000/api/notification/teacher/62c68ad4bede5107633888f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


###
//get Private Notification of parent
#GET http://localhost:8000/api/notification/parent/{{ parent_id }}
GET http://localhost:8000/api/notification/parent/62c68c94bede51076338890a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE



###
//get Private Notification of parent
#GET http://localhost:8000/api/notification/my-notification/{{ teacher_id }}&{{ parent_id }}
GET http://localhost:8000/api/notification/my-notification/62c68b2abede5107633888fb&62c68c3ebede510763388905
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


###
// create public notification
#POST http://localhost:8000/api/notification/
POST http://localhost:8000/api/notification/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE

{
  "title": "avasa",
  "content": "123412"
}


###
// create private notification
#POST http://localhost:8000/api/notification/{{ teacher_id }}&{{ parent_id }}
POST http://localhost:8000/api/notification/62c68b2abede5107633888fb&62c68c3ebede510763388905
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE

{
  "title": "Kien nghi phuc  diem",
  "content": "xin duoc xem xet lai bai thi cua chau"
}


###
// update public notification
#PUT http://localhost:8000/api/notification/public/{{ notification_id }}
PUT http://localhost:8000/api/notification/public/62ccf6b910ba28e1f72a818d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE

{
  "isCompleted": "false"
}


###
// update private notification
#PUT http://localhost:8000/api/notification/private/{{ notification_id }}
PUT http://localhost:8000/api/notification/private/62ccf976f0b91fba281523e5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE

{
  "content": "thay cho phep!",
  "isCompleted": "true"
}


###
// delet public notification
#DELET http://localhost:8000/api/notification/public/{{ notification_id }}
DELETE http://localhost:8000/api/notification/public/62ccf6e810ba28e1f72a8190
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


###
// delete private notification
#DELETE http://localhost:8000/api/notification/private/{{ notification_id }}
DELETE http://localhost:8000/api/notification/private/62ccf991f0b91fba281523eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE
