//get all Score

GET http://localhost:8000/api/teacher/score
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE



###
// create Score
#POST http://localhost:8000/dashboard/teacher/score/{{ subjectID }}&{{ studentID }}
POST http://localhost:8000/api/teacher/score/62e3436805cdd37818974354&62e343d605cdd378189743af
//POST http://localhost:8000/dashboard/teacher/score/62c699b4be8c86c9d3579870&62cbc71228ed8bda747c4445
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmUzNDRhM2Y3NWE4NjExZGFhY2MyZjgiLCJpYXQiOjE2NTkwNjI2OTF9.-dko0HCODL8LMBIACG6uwHAFnhRqMUcZIThYA_APb4c

{
  "score_ratio1": [2, 6],
  "score_ratio2": [3, 8],
  "score_ratio3": 5
}

###
// update Score
#PUT http://localhost:8000/dashboard/teacher/score/{{ score_id }}
PUT http://localhost:8000/dashboard/teacher/score/62ccdaeadbf65536c822a6a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


{
  "score_ratio1": [7, 5],
  "score_ratio2": [9, 9],
  "score_ratio3": 7
}

###

// add Score
#PUT http://localhost:8000/dashboard/teacher/score/add/{{ score_id }}
PUT http://localhost:8000/dashboard/teacher/score/add/62ccdaeadbf65536c822a6a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTIyMjR9.eZqEyxqr5k-WEm6_xd5jUdquV7czVEJ6y_Or1zcqUlE


{
  "score_ratio1": [9]
}

###

// delete Score
#DELETE http://localhost:8000/dashboard/teacher/score/{{ score_id }}
DELETE http://localhost:8000/api/teacher/score/62e349d31dc20d5c2a5e5c94
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmUzNDRhM2Y3NWE4NjExZGFhY2MyZjgiLCJpYXQiOjE2NTkwNjI2OTF9.-dko0HCODL8LMBIACG6uwHAFnhRqMUcZIThYA_APb4c

