###
//login (Admin)
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "hnt@gmail.com",
    "password": "123456"
}

###
//create parent
POST http://localhost:8000/api/admin/parents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3NTI0NjU2fQ.7JCfNVSk22yZG5h0rpRMYaWLDquYQ_LDvk-JJIP_YjQ

{
    "parent_name":"Leo",
    "parent_dateofbirth": "2001-12-01T17:00:00.000+00:00",
    "parent_address":"54 Nguyễn Lương Bằng",
    "parent_phone":"0987356234",
    "parent_email":"leo@gmail.com",
    "parent_job":"Begger",
    "parent_gender":true,
    "parent_password":"2",
    "parent_img":""
}

###
//update parent
PUT http://localhost:8000/api/admin/parents/62c68c94bede51076338890a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YjUyNmE1NTliZDhmOTRkNDBjIiwiaWF0IjoxNjU4ODAyMjY3fQ.UJ20C-Cu-dshEY_xsnL4twLCJw0BQM1osywelxz7Bt8

{
    "parent_name":"Tạ Phước Nguyên",
    "parent_dateofbirth": "2001-12-01T17:00:00.000+00:00",
    "parent_address":"906 Tôn Đức Thắng",
    "parent_phone":"0886755772",
    "parent_email":"tpn@gmail.com",
    "parent_job":"Teacher",
    "parent_gender":true,
    "parent_password":"123456",
    "parent_img":""
}

### login (Parent)
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "lmd@gmail.com",
    "password": "123456"
}

###
//create protector
POST http://localhost:8000/api/protectors/62cbd1e7a9cce1d1aa83261d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRJZCI6IjYyY2JkMWU3YTljY2UxZDFhYTgzMjYxZCIsImlhdCI6MTY1NzUyNDkxN30.t1PyfIlmDREdCbU7BVD2C-f3rEq2PVwBkIUso2xojwg

{
    "protector_name":"Cao Trí",
    "protector_address": "21 Trưng Nữ Vương",
    "protector_phone":"0341332132",
    "protector_relationship":"Wife"
}

###
// Show protector information
GET http://localhost:8000/api/protectors/get-protector/62c68c3ebede510763388905
Content-Type: application/json

###
// Show student information
GET http://localhost:8000/api/student/get-student/62e3459c5e8db746fb21089b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTA1MDExfQ.WOdIy-Kcc5rX47HbmSVe-XUQhu41asw5vo4zeSr56_o


###
// Show Parent information
GET http://localhost:8000/api/protectors/get-protector/62cbd1e7a9cce1d1aa83261d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRJZCI6IjYyY2JkMWU3YTljY2UxZDFhYTgzMjYxZCIsImlhdCI6MTY1NzUyNDkxN30.t1PyfIlmDREdCbU7BVD2C-f3rEq2PVwBkIUso2xojwg


###
// GET
GET http://localhost:8000/api/admin/parents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU5MDYxMzk3fQ.bwA4PyzZDd_h3oT1gUnVryWlCS4P_2BuQzKsHgvVw_Y
###
// delete
DELETE  http://localhost:8000/api/admin/parents/62ce923b89445ec45e6021f2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3NTI0NjU2fQ.7JCfNVSk22yZG5h0rpRMYaWLDquYQ_LDvk-JJIP_YjQ

###
// get parent by id
GET  http://localhost:8000/api/admin/parents/62c68c3ebede510763388905
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTA1MDExfQ.WOdIy-Kcc5rX47HbmSVe-XUQhu41asw5vo4zeSr56_o

###
// delete
DELETE  http://localhost:8000/api/protectors/62e3971fd00aaeddd6719835
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRJZCI6IjYyZTM0NTljNWU4ZGI3NDZmYjIxMDg5YiIsImlhdCI6MTY1OTA4MjM2Mn0.ERsbrIHtouoxuwf3fFgglLC_WtNyJsuy_csoHO7iF78