//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "4",
    "password": "4"
}
###
//teacher create student
POST http://localhost:8000/dashboard/teacher/student/create-student/62c2aef039a7880ce4a386a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

{
    "student_fullname" : "Marine",
    "student_age":20,
    "student_gender":true,
    "student_image": "image link",
    "student_behavior":"Trungbinh"
}
###
//teacher get all student
GET http://localhost:8000/dashboard/teacher/student/get-all-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

###
//teacher get student by teacher id
GET http://localhost:8000/dashboard/teacher/student/get-student-by-teacher-id/62c2aef039a7880ce4a386a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

###
//teacher get student by student id
GET http://localhost:8000/dashboard/teacher/student/get-student-by-student-id/62c640bac572db9e5810e334&62bec1eace300d797af8a13b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

###
//teacher update student by id_student
PUT http://localhost:8000/dashboard/teacher/student/update-student/62c523c7a574db45a8646b1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

{
    "student_fullname": "Marinee",
    "student_age": 22,
    "student_gender" : true,
    "student_image": "image link ne"
}
###
//teacher delete student
DELETE  http://localhost:8000/dashboard/teacher/student/delete-student/62c523c7a574db45a8646b1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc
