//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "4",
    "password": "4"
}
###
//logoout
get http://localhost:8000/api/authentication/logout
Content-Type: application/json
###
//teacher create student
POST http://localhost:8000/dashboard/teacher/student/create-student/62c68b2ebede510763388900
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

{
    "student_fullname" : "Polly",
    "student_age":8,
    "student_gender":false,
    "student_image": "image link"
}
###
//teacher get all student
GET http://localhost:8000/dashboard/teacher/student/get-all-student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

###
//teacher get student by teacher id
GET http://localhost:8000/dashboard/teacher/student/get-student-by-teacher-id/62c68ad4bede5107633888f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

###
//teacher get student by student id
GET http://localhost:8000/dashboard/teacher/student/get-student-by-student-id/62c69bb9be8c86c9d3579921
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

###
//teacher update student by id_student
PUT http://localhost:8000/dashboard/teacher/student/update-student/62c78fb46008f5e67d096b97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4

{
    "student_fullname": "Violet",
    "student_age": 17,
    "student_gender" : false,
    "student_image": "image link !"
}
###
//teacher delete student
DELETE  http://localhost:8000/dashboard/teacher/student/delete-student/62c78fb46008f5e67d096b97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTcxODMxNTB9.zr4B2yhwd-rn2LKywhbrkx-xLL1gwWU8kI5z9PmfeP4
