//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "keren@gmail.com",
    "password": "123456"
}

###
//add subject to student
//subjectID&&:studentID
GET  http://localhost:8000/api/teacher/subjects/add-subjects-to-student/62e3436805cdd37818974354&62e343d605cdd378189743af
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU5MDAwOTU0fQ.kuJAxoRBOlZeOLQ4sI1UN64ZTLcqhQXElMlkGEvoibc


###
//add subject to grade and student
//subjectID&:gradeID&:studentID
GET  http://localhost:8000/api/teacher/subjects/add-subjects-to-grade-and-student/62c699b4be8c86c9d3579870&62c6999bbe8c86c9d3579862&62cbc71228ed8bda747c4445
#GET  http://localhost:8000/dashboard/teacher/subjects/add-subjects-to-grade-and-student/62c69a1abe8c86c9d3579897&62c69998be8c86c9d357985f&62cbc71228ed8bda747c4445
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4ODE2ODc0fQ.Qo7_Z9Tc5Py6me16qa6g18DZeUhc2YHyfH12S6fLAJU

###
//create subject
//grade 1 : 62c69998be8c86c9d357985f
//grade 2 : 62c6999bbe8c86c9d3579862
//grade 3 : 62c6999ebe8c86c9d3579865
//grade 4 : 62c699a0be8c86c9d3579868
//grade 5 : 62c699a4be8c86c9d357986b
POST http://localhost:8000/api/subjects/create-subject/62c6999bbe8c86c9d3579862
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NzE0MzIwfQ.q04B8wBPSj4JUz-0AfTt2bGoUhEJ8VO_9RZ_s7_Nhpc

{
    "subject_name" : "English",
    "subject_ratio" : 1
}

###
// get subject
// get subject by id
GET http://localhost:8000/api/subjects/get-subject-by-id/62c5048288e28092b08a0b1c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMWViZWRlNTEwNzYzMzg4OTE0IiwiaWF0IjoxNjU4MTMwODgwfQ.CUWOwDELYZ7AOsm9SXhp4wi1adrTYj3dXlkT1GaHzVc

###
//get all subject
GET http://localhost:8000/api/subjects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTc1NTU0fQ.7Kx5HA7FFfc9Hci0r1CJ1TZOq_FyI6reteRT__UCqLE


###
//get subject by grade ID
GET http://localhost:8000/api/subjects/62c69998be8c86c9d357985f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMWViZWRlNTEwNzYzMzg4OTE0IiwiaWF0IjoxNjU4MTMwODgwfQ.CUWOwDELYZ7AOsm9SXhp4wi1adrTYj3dXlkT1GaHzVc

###
// get subject
// get subject by id
GET http://localhost:8000/api/subjects/get-subject-by-id/62e210ed5cb4fc239eed778e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTc1NTU0fQ.7Kx5HA7FFfc9Hci0r1CJ1TZOq_FyI6reteRT__UCqLE
###
//get student by subject id
GET http://localhost:8000/api/subjects/get-student-by-subject-id/62e737ed9d99bc625a0bd83c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTc1NTU0fQ.7Kx5HA7FFfc9Hci0r1CJ1TZOq_FyI6reteRT__UCqLE

###
// update
PUT http://localhost:8000/api/subjects/62e210ed5cb4fc239eed778e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTc1NTU0fQ.7Kx5HA7FFfc9Hci0r1CJ1TZOq_FyI6reteRT__UCqLE

{
    "subject_name" : "Test 3",
    "subject_ratio" : 1
}

###
DELETE http://localhost:8000/api/subjects/62e210ed5cb4fc239eed778e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4NzE0MzIwfQ.q04B8wBPSj4JUz-0AfTt2bGoUhEJ8VO_9RZ_s7_Nhpc

###
GET http://localhost:8000/api/subjects/get-subject-from-student/62e0e9689fe1de43d8845ffd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4OTc1NTU0fQ.7Kx5HA7FFfc9Hci0r1CJ1TZOq_FyI6reteRT__UCqLE
