//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "4",
    "password": "4"
}

###
// // add subject to grade and student
GET  http://localhost:8000/dashboard/teacher/subjects/add-subjects-to-grade-and-student/62c4090cb0836bed0fe1f518&62c3e18402d045ac2705de51&62c640bac572db9e5810e334
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

###
// get subject
GET http://localhost:8000/api/subjects/get-subject-by-id/62c5048288e28092b08a0b1c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTc3NTR9.FWH2aw2CU47RDU2rKXUb672j53RjRUVfQ_Td9PdptgE