//resgiter
# POST http://localhost:8000/authentication/register
# Content-Type: application/json

# {
#     "account_username": "teacher",
#     "account_password": "1",
#     "account_role" : "Teacher"
# }

###

//login
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "nkd@gmail.com",
    "password": "1"
}

###
//add subject to grade and student
//subjectID&:gradeID&:studentID
GET  http://localhost:8000/dashboard/teacher/subjects/add-subjects-to-grade-and-student/62c69a48be8c86c9d35798ca&62c69998be8c86c9d357985f&62cbc71228ed8bda747c4445
GET  http://localhost:8000/dashboard/teacher/subjects/add-subjects-to-grade-and-student/62c69a1abe8c86c9d3579897&62c69998be8c86c9d357985f&62cbc71228ed8bda747c4445
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmM2OGFkNGJlZGU1MTA3NjMzODg4ZjYiLCJpYXQiOjE2NTc1OTM2NjZ9.CZkMCBEEfw6yytVghIBNwHqkfpxNCUD82_XYf4MsPZs

###
//create subject
//grade 1 : 62c69998be8c86c9d357985f
//grade 2 : 62c6999bbe8c86c9d3579862
//grade 3 : 62c6999ebe8c86c9d3579865
//grade 4 : 62c699a0be8c86c9d3579868
//grade 5 : 62c699a4be8c86c9d357986b
POST http://localhost:8000/dashboard/teacher/subjects/create-subject/62c699a4be8c86c9d357986b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVySWQiOiI2MmMyYWVmMDM5YTc4ODBjZTRhMzg2YTQiLCJpYXQiOjE2NTY5ODY4ODh9.6r0qdOlVjBTd3nOc-Sta2almy77UzG5BMXvhhLu2hlc

{
    "subject_name" : "English",
    "subject_ratio" : 1
}

###
// get subject
// get subject by id
GET http://localhost:8000/api/subjects/get-subject-by-id/62c5048288e28092b08a0b1c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTc3NTR9.FWH2aw2CU47RDU2rKXUb672j53RjRUVfQ_Td9PdptgE

###
//get all subject
GET http://localhost:8000/api/subjects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMyOGEzODRlNWUyMDU4ZTUwZDIyNDYiLCJpYXQiOjE2NTY5MTc3NTR9.FWH2aw2CU47RDU2rKXUb672j53RjRUVfQ_Td9PdptgE
