###
//login (Admin)
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "keren@gmail.com",
    "password": "123456"
}


###
//create admin
POST http://localhost:8000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3ODc0ODM3fQ.9JhTeeaGsDURamjVZrGeinDHOB4xO9YR6SYaYF6bbS8

{
    "admin_username": "caominhtri2",
    "admin_password": "123456",
    "admin_email": "leo3@gmail.com"
}

###
PUT http://localhost:8000/api/admin/62d0d6ef7fdc3b0205a2749e
{
    "admin_username": "Keren",
    "admin_password": "3",
    "admin_email": "keren@gmail.com"
}

###
GET http://localhost:8000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3ODc0ODM3fQ.9JhTeeaGsDURamjVZrGeinDHOB4xO9YR6SYaYF6bbS8



###
PUT http://localhost:8000/api/admin/62c68d1ebede510763388914
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3ODc0ODM3fQ.9JhTeeaGsDURamjVZrGeinDHOB4xO9YR6SYaYF6bbS8

{
    "admin_username": "Nguyễn Hữu Dinh",
    "admin_password": "123456",
    "admin_email": "nhd_admin@gmail.com"
}