###
//login (Admin)
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "hnt@gmail.com",
    "password": "3"
}

###
//create parent
POST http://localhost:8000/api/admin/parents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJjNjhkMTNiZWRlNTEwNzYzMzg4OTBmIiwiaWF0IjoxNjU3NTI0NjU2fQ.7JCfNVSk22yZG5h0rpRMYaWLDquYQ_LDvk-JJIP_YjQ

{
    "parent_name":"Trí Minh Cao",
    "parent_dateofbirth": "2001-12-01T17:00:00.000+00:00",
    "parent_address":"54 Nguyễn Lương Bằng",
    "parent_phone":"0987356234",
    "parent_email":"cmt@gmail.com",
    "parent_job":"Begger",
    "parent_gender":true,
    "parent_password":"2",
    "parent_img":""
}

### login (Parent)
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "email": "cmt@gmail.com",
    "password": "2"
}

###
//create protector
POST http://localhost:8000/api/protectors/62cbd1e7a9cce1d1aa83261d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRJZCI6IjYyY2JkMWU3YTljY2UxZDFhYTgzMjYxZCIsImlhdCI6MTY1NzUyNDkxN30.t1PyfIlmDREdCbU7BVD2C-f3rEq2PVwBkIUso2xojwg

{
    "protector_name":"Cao Trí",
    "protector_address": "21 Trưng Nữ Vương",
    "protector_phone":"0341332132",
    "protector_relationship":"Wife"
}

###
// Show protector information
GET http://localhost:8000/api/protectors/get-protector/62c68c3ebede510763388905
Content-Type: application/json


###
// Show Parent information
GET http://localhost:8000/api/protectors/get-protector/62cbd1e7a9cce1d1aa83261d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJlbnRJZCI6IjYyY2JkMWU3YTljY2UxZDFhYTgzMjYxZCIsImlhdCI6MTY1NzUyNDkxN30.t1PyfIlmDREdCbU7BVD2C-f3rEq2PVwBkIUso2xojwg
